# Generated by Django 3.2.8 on 2022-03-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20220311_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
