# Generated by Django 3.2.8 on 2022-03-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20220312_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='price',
            new_name='total_price',
        ),
    ]
