# Generated by Django 3.2.8 on 2022-03-11 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20220312_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
            preserve_default=False,
        ),
    ]
