# Generated by Django 3.2.8 on 2022-03-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_alter_cartitem_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='total_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='content_type',
        ),
    ]
